### ISSUE TITLE
Include Reactions and Responses to Messages?

### ISSUE THREAD

**Issue by tlcameron3** [chrrel/whatsapp-exporter#16]
Everything here is working fine, except all reactions (emoji reactions) and response details (whether a message is a response to another message) are missing. Is there a reason why these are not here, and everything else is so thoroughly included? These are included in the Database file itself, yes? I will be looking into whether I can add this functionality myself, but I will need to figure out how to understand the db file first. This would perhaps be a simple fix to include these options

**Comment by chrrel** [comment]
Hi @tlcameron3,
I guess this information is included in the database nowadays. Probably this feature did not exist when I did my export and therefore is not relevant for me. I am sorry, but I will not put effort into this idea.

Cheers
