### ISSUE TITLE
How to filter by specific contact?

### ISSUE THREAD

**Issue by rvega** [chrrel/whatsapp-exporter#17]
Hi, thanks for all the great work here. Working great so far with Android and linux! 

Question: 

Which parts of the code should I edit in order to only export the history of a particular contact? I tried to follow the instructions here https://github.com/chrrel/whatsapp-exporter/issues/12 but the line numbers and the queries don't match what I see in .venv/.../Whatsapp_Chat_Exporter/*.py 
(I installed with pip using a venv)

**Comment by chrrel** [comment]
Hi @rvega,
to filter for a specific contact you need to adapt the SQL queries. This is described in the _Usage_ section of the [README](https://github.com/chrrel/whatsapp-exporter/blob/main/README.md).

I guess you might want to double-check the the library you are working with as there is no directory called `Whatsapp_Chat_Exporter` in this project. Seems like you installed a different project: [Whatsapp-Chat-Exporter](https://github.com/KnugiHK/Whatsapp-Chat-Exporter/).

**Comment by rvega** [comment]
My bad, thanks for the reply!
