### ISSUE TITLE
Why i get this report when i try to make it as html in termux(anyway there is no such problem while i tried make it as txt)

### ISSUE THREAD

**Issue by ZonateMeteor208** [chrrel/whatsapp-exporter#19]
This is what shown in my screen
Pls return me there is about 670mb of chats in my msgstore and they are so important
![IMG_20240331_065341.jpg](https://github.com/chrrel/whatsapp-exporter/assets/83952957/399b3a2a-d4ad-43b0-b82e-d5eec1296764)

**Comment by chrrel** [comment]
Hey,

the error displayed in your screenshot says `IsADirectoryError`. Are you sure that you provided a file path for the HTML output in the configuration? 

`html_output_path` needs to be a file, not a directory. See: https://github.com/chrrel/whatsapp-exporter/blob/ae12663b2008777750ad92d3fdd860c0d76190cf/whatsapp-exporter/config.cfg#L13

**Comment by ZonateMeteor208** [comment]
Oh my fault i will try then hit you again if doesnt work

**Comment by ZonateMeteor208** [comment]
THANK YOU A LOT!!!
you are a life saver after all these months i get access to my messages thx bro!
Is there a method to apply these db files to my current wp?

**Comment by chrrel** [comment]
Glad it worked. :)
For importing the data back to WhatsApp, you will probably need to use the encrypted backup. To export your current databse, you need to decrypt it first. I have linked some information in the README. Unfortunately, I cannot help you with that.

**Comment by ZonateMeteor208** [comment]
Oh well, its a bit out of content but anyway  I got a question for u while I check my old wp data I founded a folder named shared_prefs then I examine it meanwhile i found a xml file named Whatsapriv.xml and there is some encrypted like text and they had a Variability of length according to each number i found a so long one and the number attached with is my old gf one and all messages from she deleted so long ago also they wasn't appear in extractor i attached a video for better understanding for u if these encrpyted texts are messages how can we decrypt them 
[]()https://streamable.com/o4maxd

**Comment by chrrel** [comment]
I do not know and I also do cannot help you with that.
