### ISSUE TITLE
Code for new features

### ISSUE THREAD

**Issue by dani-91** [chrrel/whatsapp-exporter#4]
Hi, thank you very much for your code. It was very helful for me.

I write this as an issue because I don't know where's a better place to message you.
I changed the code (the sql) to support the iphone whatsapp database tables and I added code to display media like audio, video and images because  I needed it for my own. If you want, I can share the code with you. It was quick and dirty but maybe you can use it.

**Comment by chrrel** [comment]
Hi @dani-91,
thanks for reaching out. I'm glad this project was useful for you.
While I currently do not plan to integrate media output to this project, the iOS part seems interesting to me. Depending on the necessary work, I could imagine integrating this as well.

You could either share this via a merge request or you can invite me to a private repository in case you want to keep your work private in the beginning. 
Do you also have test data for iOS? Right now I do not have access to an iOS Whatsapp database.

**Comment by dani-91** [comment]
Hi @chrrel,
yes, I'll try to make a merge request. It's the first time I will do this :)

**Comment by newdrkhckr** [comment]
> Hi, thank you very much for your code. It was very helful for me.
> 
> I write this as an issue because I don't know where's a better place to message you. I changed the code (the sql) to support the iphone whatsapp database tables and I added code to display media like audio, video and images because I needed it for my own. If you want, I can share the code with you. It was quick and dirty but maybe you can use it.

Hi, Your idea of implementing media into this project is excited me. I would appreciate same thing you did with your own. 
I want to add media files into output, same like you wanted. Another thing that i had anroid backup database. Do you think that will it cause a problem ? I would like to discuss that if you have time.

But i dont know how to contact you. If you still have the code for implementing media, can you share it with me ? Again i dont know how and where can you share it but i would grealtly appreciete it.

**Comment by scorpioRED** [comment]
@dani-91 Where I can find your fork which works with IOS backup?
