### ISSUE TITLE
Any plans for supporting media?

### ISSUE THREAD

**Issue by karanrajpal14** [chrrel/whatsapp-exporter#9]
As the title states, do you have any plans of supporting media as well?
The messages table already references the media file and they're accessible via the media folder so it might be doable?
What do you think?

I mainly use this to archive older conversations that I may need to reference in the future and it would be helpful if media was included as well.

**Comment by chrrel** [comment]
Hi,
I am sorry to tell you that such a feature is not planned right now.
Additionally, this also might get tricky. Yes, the files are referenced in the database, so you could include them in the HTML output as well. But with the current architecture of this tool consisting of just a single HTML file, this might cause significant performance issues. Especially in large message databases this would mean that lots of images had to be loaded into the page. This might easily overwhelm the browser.

**Comment by karanrajpal14** [comment]
I understand. We could only just move the media and link to it locally. Don't need to display them inline in the conversation, which I understand is more difficult.

Or at the very least, just consider outputting the filename as a message in the conversation so that it's easier to manually look the file up. That's better than just ignoring them outright.

What do you think?

**Comment by chrrel** [comment]
Yes, might be a possible solution. Feel free to create a pull request. :)
